# App Version: 2.4
version: '3.8'  # Newer Docker Compose version. This is a deployment config for portainer with docker swarm. It pulls from the github repo.

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Ash
      POSTGRES_PASSWORD: Ketchum
      POSTGRES_DB: pokeappdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Ash"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  
  redis:
    image: redis:latest
    ports:
      - target: 6379
        published: 6379
        protocol: tcp
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  pokeapp:
    image: evilgenius13/pokeapp:v2.4
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    environment:
      SECRET_KEY: pokemon
      DATABASE_URL: postgresql://Ash:Ketchum@postgres:5432/pokeappdb
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: /app/start-pokeapp.sh
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s