version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: Ash
      POSTGRES_PASSWORD: Ketchum
      POSTGRES_DB: pokeappdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Ash"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  pokeapp:
    image: evilgenius13/pokeapp:v2.3
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: Ash
      POSTGRES_PASSWORD: Ketchum
      SECRET_KEY: pokemon
      DATABASE_URL: postgresql://Ash:Ketchum@postgres:5432/pokeappdb
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    command: /app/start-pokeapp.sh  # Update the command to use your start script
