name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build and start Docker containers
      run: |
        docker-compose up -d

    - name: Wait for the server to be up
      run: |
        while ! curl -s http://localhost:5000/ > /dev/null; do
          sleep 1
        done

    - name: Run tests
      run: |
        docker exec -t pokebackpackfinal_pokeapp_1 python3 -m unittest discover -s /app/poke_app/ -p '*test.py'

    - name: Stop Docker containers
      run: docker-compose down

  build:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        echo "DOCKER_TAG=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        docker build -t evilgenius13/pokeapp:${DOCKER_TAG} .
        docker push evilgenius13/pokeapp:${DOCKER_TAG}